spring.application.name=backend

spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.password=123
#spring.datasource.username=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#
#minio.url=http://localhost:9000
#minio.access.name=admin
#minio.access.secret=admin123
#minio.bucket.name=profile-image
#
#app.cors.allowed-origins=http://localhost:3000

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

minio.url=${MINIO_URL}
minio.access.name=${MINIO_ACCESS_NAME}
minio.access.secret=${MINIO_ACCESS_SECRET}
minio.bucket.name=${MINIO_BUCKET_NAME}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}

